name: Build and Deploy to Azure Container Registry

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: webappdio.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build da imagem
        run: docker build -t webappdio.azurecr.io/fastapi-webapp:latest .

      - name: Push imagem para o ACR
        run: docker push webappdio.azurecr.io/fastapi-webapp:latest
